# Generated by Django 4.1.7 on 2023-06-13 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id_categorie', models.IntegerField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_categorie', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id_produit', models.IntegerField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_produit', models.CharField(max_length=100)),
                ('prix_produit', models.IntegerField()),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epicerie.categorie')),
            ],
        ),
        migrations.CreateModel(
            name='StockRestant',
            fields=[
                ('id_restant', models.IntegerField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_restant', models.IntegerField()),
                ('date_restant', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='TotalStock',
            fields=[
                ('id_total', models.IntegerField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField()),
                ('date_total', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Vendre',
            fields=[
                ('id_vendre', models.IntegerField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_vendre', models.FloatField(blank=True, null=True)),
                ('prix_total_vendre', models.IntegerField()),
                ('date_vendre', models.DateField()),
                ('produit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='epicerie.produit')),
            ],
        ),
        migrations.CreateModel(
            name='StockProduit',
            fields=[
                ('id_stock', models.IntegerField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_stock', models.FloatField()),
                ('prix_total', models.IntegerField()),
                ('date_stock', models.DateField(blank=True)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epicerie.produit')),
            ],
        ),
        migrations.CreateModel(
            name='Inventaire',
            fields=[
                ('id_inventaire', models.IntegerField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nb_produit', models.FloatField()),
                ('total_prix', models.IntegerField()),
                ('date_inventaire', models.DateField()),
                ('stock_produit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='epicerie.stockproduit')),
            ],
        ),
    ]
