# Generated by Django 4.1.7 on 2023-06-13 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('epicerie', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventaire',
            name='stock_produit',
        ),
        migrations.AddField(
            model_name='inventaire',
            name='produit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='epicerie.produit'),
        ),
    ]
